language: node_js
node_js:
  - '4'
branches:
  only:
  - master
cache:
  directories:
    - node_modules
after_success:
  - npm run coverage
deploy:
  provider: npm
  email: agstanki@gmail.com
  api_key:
    secure: v3hpVJYKN1LkNk69rrorjovucZ4ePcBUo7CNFWmko/4FdJ1xES3D1EmkngzDtv1MjffL0/8O+kaQf6ddZXAu2ZgeWtMNkZ7F/5VetJo50rtlRaQ1ggZM5Rl92McJlDIr7ozKV1nN0zgDAJkGVXdEFqWgdE6JIz303/YtRMbtylrDTf7PD68ElgwsVBxsvDyvzjcXCbrdE+wPR9RTPjTtWUYw0ggqAEnP9hdzUXumxaHX1WG4PRJQjx/uD7pAY6nugbBj3DOMe9M4bsWgdFDopWI48jPLa+4eFoVmQLttA67oTAaHj3THi1j37rP0Gjc8VaVtm8oj6NzsCCJGT58yaZjhodoljWqmJRCIbu/fD9WDwn7y7kHaSeaN6cSsdAKa0EwZhXNPa8A0OU4mJLd1/JkN2vCIA5L68K9Z2Qhgh5LtNQPO3T1tbDGekeNc4s7xwPtUtd13eWrmZFuv+Eddg7xfdNzfENrMEzuCK8mgfiuyv/4o9NYshLbF1CLoWAe5o+0rX13i+xdU6ae8PPgRKddrCPMJ2x+dGhFeobb12zW5eb8EXWyyZf3MwnLax9O/lk31CHHcTvhO9jkK+c0trEARqlP5Mdr+nLqPgfAKbAe4kfI1sSfutHNzspzJAYsG+K3EOa4JLKkjYj6RR2AmIJ67Lwt8B2PJuZMkh/dqoGo=
